//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbrellaProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmbrellaProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        public static string AcceptBtnContent {
            get {
                return ResourceManager.GetString("AcceptBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY ACTIVATION.
        /// </summary>
        public static string ActivatePromoKey_textblock {
            get {
                return ResourceManager.GetString("ActivatePromoKey_textblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add scripts.
        /// </summary>
        public static string AddScripts_tooltip {
            get {
                return ResourceManager.GetString("AddScripts_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti VAC.
        /// </summary>
        public static string AntiVAC {
            get {
                return ResourceManager.GetString("AntiVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiVAC: injecting error, please restart the launcher by administrator and disable antiviruses and firewalls.
        /// </summary>
        public static string ANTIVAC_INJECT_ERROR {
            get {
                return ResourceManager.GetString("ANTIVAC_INJECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiVAC: OpenProcess error.
        /// </summary>
        public static string ANTIVAC_OPENPROCESS_ERROR {
            get {
                return ResourceManager.GetString("ANTIVAC_OPENPROCESS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiVAC: failed getting Steam path (steam.exe is not found).
        /// </summary>
        public static string ANTIVAC_STEAMPATH_ERROR {
            get {
                return ResourceManager.GetString("ANTIVAC_STEAMPATH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start the Steam and press Start button again.
        /// </summary>
        public static string AskForSteamStart {
            get {
                return ResourceManager.GetString("AskForSteamStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization: wrong login or password.
        /// </summary>
        public static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZING.
        /// </summary>
        public static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scripts update.
        /// </summary>
        public static string AutoScriptsUpdate {
            get {
                return ResourceManager.GetString("AutoScriptsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CancelBtnContent {
            get {
                return ResourceManager.GetString("CancelBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat: game files check error, you&apos;d update game client or wait for Umbrella server update, please try again later.
        /// </summary>
        public static string CHEAT_CRCCHECK_ERROR {
            get {
                return ResourceManager.GetString("CHEAT_CRCCHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat: failed getting Dota2 path, you probably never launched Dota2.
        /// </summary>
        public static string CHEAT_DOTAPATH_ERROR {
            get {
                return ResourceManager.GetString("CHEAT_DOTAPATH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat: injecting error.
        /// </summary>
        public static string CHEAT_INJECT_ERROR {
            get {
                return ResourceManager.GetString("CHEAT_INJECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat: init protection error..
        /// </summary>
        public static string CHEAT_PROTECTION_ERROR {
            get {
                return ResourceManager.GetString("CHEAT_PROTECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEAT STATUS.
        /// </summary>
        public static string CheatStatus {
            get {
                return ResourceManager.GetString("CheatStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKING FOR UPDATE.
        /// </summary>
        public static string CheckingForUpdate {
            get {
                return ResourceManager.GetString("CheckingForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC check.
        /// </summary>
        public static string CRCcheck {
            get {
                return ResourceManager.GetString("CRCcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella server.
        /// </summary>
        public static string CurrentServer_TextBlock {
            get {
                return ResourceManager.GetString("CurrentServer_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all scripts.
        /// </summary>
        public static string DeleteScripts_tooltip {
            get {
                return ResourceManager.GetString("DeleteScripts_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOADING RESOURCES.
        /// </summary>
        public static string Downloading_images {
            get {
                return ResourceManager.GetString("Downloading_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOADING UPDATE.
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailHint {
            get {
                return ResourceManager.GetString("EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ERROR_TextBlock {
            get {
                return ResourceManager.GetString("ERROR_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        public static string Expire_TextBlock {
            get {
                return ResourceManager.GetString("Expire_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORUM URL.
        /// </summary>
        public static string ForumUrl_textblock {
            get {
                return ResourceManager.GetString("ForumUrl_textblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button below to open forum thread about the script with relative language.
        /// </summary>
        public static string ForumUrlDesc_textblock {
            get {
                return ResourceManager.GetString("ForumUrlDesc_textblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free days.
        /// </summary>
        public static string FREE_DAYS {
            get {
                return ResourceManager.GetString("FREE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game launch Options.
        /// </summary>
        public static string GameLaunchOptions {
            get {
                return ResourceManager.GetString("GameLaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWID is banned.
        /// </summary>
        public static string HWID_BANNED {
            get {
                return ResourceManager.GetString("HWID_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization: wrong HWID.
        /// </summary>
        public static string HWID_ERROR {
            get {
                return ResourceManager.GetString("HWID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect lua path, it only supports github .lua path or repository.
        /// </summary>
        public static string IncorrectLuaPath {
            get {
                return ResourceManager.GetString("IncorrectLuaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing: kernel error.
        /// </summary>
        public static string INIT_KERNEL_ERROR {
            get {
                return ResourceManager.GetString("INIT_KERNEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INJECTING UMBRELLA.
        /// </summary>
        public static string Injecting {
            get {
                return ResourceManager.GetString("Injecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_TextBlock {
            get {
                return ResourceManager.GetString("Language_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCHING DOTA.
        /// </summary>
        public static string LaunchingDota {
            get {
                return ResourceManager.GetString("LaunchingDota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFETIME SUB..
        /// </summary>
        public static string LIFETIME {
            get {
                return ResourceManager.GetString("LIFETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel: product loading error.
        /// </summary>
        public static string LOAD_KERNEL_ERROR {
            get {
                return ResourceManager.GetString("LOAD_KERNEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send scripts list.
        /// </summary>
        public static string LOAD_PRIVATE_SCRIPTS_ERROR {
            get {
                return ResourceManager.GetString("LOAD_PRIVATE_SCRIPTS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOADING.
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong product ID.
        /// </summary>
        public static string LOADPRODUCT_NOTFOUND {
            get {
                return ResourceManager.GetString("LOADPRODUCT_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string LoginBtnContent {
            get {
                return ResourceManager.GetString("LoginBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN SETTINGS.
        /// </summary>
        public static string MainSettings_TextBlock {
            get {
                return ResourceManager.GetString("MainSettings_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (turn it on when Dota2 is started too early).
        /// </summary>
        public static string ManualSteamLaunch_hint {
            get {
                return ResourceManager.GetString("ManualSteamLaunch_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Steam launched accepting.
        /// </summary>
        public static string ManualSteamLaunched {
            get {
                return ResourceManager.GetString("ManualSteamLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON UPDATING.
        /// </summary>
        public static string OnUpdatingStatus {
            get {
                return ResourceManager.GetString("OnUpdatingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASTE SCRIPTS PATH.
        /// </summary>
        public static string PasteLuaPath_textblock {
            get {
                return ResourceManager.GetString("PasteLuaPath_textblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private scripts.
        /// </summary>
        public static string PrivateScripts {
            get {
                return ResourceManager.GetString("PrivateScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key has already been activated.
        /// </summary>
        public static string PromoKey_already_used {
            get {
                return ResourceManager.GetString("PromoKey_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the subscription key.
        /// </summary>
        public static string PromoKey_hint {
            get {
                return ResourceManager.GetString("PromoKey_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may active the next promo key in.
        /// </summary>
        public static string PromoKey_limit {
            get {
                return ResourceManager.GetString("PromoKey_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription key does not exist.
        /// </summary>
        public static string PromoKey_no_exists {
            get {
                return ResourceManager.GetString("PromoKey_no_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key successfully activated.
        /// </summary>
        public static string PromoKey_success {
            get {
                return ResourceManager.GetString("PromoKey_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key activation.
        /// </summary>
        public static string PromoKeyOption_textblock {
            get {
                return ResourceManager.GetString("PromoKeyOption_textblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again.
        /// </summary>
        public static string RememberMyChoice {
            get {
                return ResourceManager.GetString("RememberMyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: remote server is not available.
        /// </summary>
        public static string RemoteServerUnavailable {
            get {
                return ResourceManager.GetString("RemoteServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRIPT CONFLICT.
        /// </summary>
        public static string ScriptConflict_textblock {
            get {
                return ResourceManager.GetString("ScriptConflict_textblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There script conflict has occurred while updating. Press the Accept button to get the latest github version or Cancel to keep local version..
        /// </summary>
        public static string ScriptConflictDesc_textblock {
            get {
                return ResourceManager.GetString("ScriptConflictDesc_textblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRIPTS.
        /// </summary>
        public static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing: server connection error, please try again later.
        /// </summary>
        public static string SERVER_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("SERVER_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing: server connection error, please try again later.
        /// </summary>
        public static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string Start_TextBlock {
            get {
                return ResourceManager.GetString("Start_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam has been launched but please open Steam game library and press the OK button.
        /// </summary>
        public static string SteamIsLaunched {
            get {
                return ResourceManager.GetString("SteamIsLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEAM REBOOTING.
        /// </summary>
        public static string SteamRebooting {
            get {
                return ResourceManager.GetString("SteamRebooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription time is expired, please update subscription.
        /// </summary>
        public static string SubTimeExpired {
            get {
                return ResourceManager.GetString("SubTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string SUCCESS_TextBlock {
            get {
                return ResourceManager.GetString("SUCCESS_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCES UNPACKING.
        /// </summary>
        public static string Unpacking_images {
            get {
                return ResourceManager.GetString("Unpacking_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all scripts.
        /// </summary>
        public static string UpdateScripts_tooltip {
            get {
                return ResourceManager.GetString("UpdateScripts_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription.
        /// </summary>
        public static string UpdateSubscription {
            get {
                return ResourceManager.GetString("UpdateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATING.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update: remote update server is not available.
        /// </summary>
        public static string UpdatingFailed {
            get {
                return ResourceManager.GetString("UpdatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to lua script or github repository.
        /// </summary>
        public static string URLtoLuaPath_hint {
            get {
                return ResourceManager.GetString("URLtoLuaPath_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User scripts.
        /// </summary>
        public static string UserScripts {
            get {
                return ResourceManager.GetString("UserScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string WARNING_TextBlock {
            get {
                return ResourceManager.GetString("WARNING_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
